name: 'Create PR to other branches, on commits to a branch'
description: 'Commits, pushes a new PR branch and creates PR for the commits.'
author: '@himadrisingh'
inputs:
  pr_branch:
    description: 'Target Branch to create PR'
    required: true
  pr_labels:
    description: 'Labels for the new PR'
    required: false
    default: 'autocreated'
  opt_in_message:
    description: 'If set, PRs will only be triggered if this message is found in the last commit.'
    required: false
  merge_strategy:
    description: 'Options to pass to git cherry-pick to adjust the merging strategy.'
    required: false
    default: '--strategy=recursive'
runs:
  using: 'docker'
  image: 'Dockerfile'
